name: cocktail
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  go_router: ^13.2.0
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.7.0
  simple_shadow: ^0.3.1
  collection: ^1.18.0
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  flex_color_scheme: ^7.3.1
  uuid: ^4.4.0
  circular_menu: ^4.0.0
  dio: ^5.4.3+1
  shimmer: ^3.0.0
  skeletonizer: ^1.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

